# Reference : https://docs.travis-ci.com/user/languages/android/
language: android

# Only trusty distributions are supported for Android.
dist: trusty

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-29.0.2

    # The SDK version used to compile your project
    - android-29

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    # Accept all Android licenses.
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

jobs:
  include:
    - script:
        - touch emptyFileForRelease
        - ./gradlew clean assembleDebug # testProductionAPIDebugUnitTest
        # - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_REPO_SLUG" == "heig-PRO-b04/android-frontend" ]];
        #   then bash ./.travis/deploy.sh;
        #   cd app/build/outputs/apk/productionAPI/debug/;
        #   curl -F document=@app-productionAPI-debug.apk https://api.telegram.org/bot${TL_TOKEN}/sendDocument?chat_id=@rockindev;
        #   fi
